name: GitHub Secrets Test

on: [push]

jobs:
  test-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print the Secret
        env:
          SUPER_SECRET: ${{ secrets.MY_SECRET_KEY }}
        run: |
         echo "Testing GitHub Secrets..."
         echo "my password is: $SUPER_SECRET"
         