name: System Checker Pipeline

on: [push]

jobs:
   check-system:
      runs-on: ubuntu-latest
      steps:
        - name: Checktout Code
          uses: actions/chectout@v3

        - name: Check Ubuntu Version
          run: cat /etc/os-release

        - name: List All Files
          run: ls -la
          